

export const translate = {
  EN: {
  //!  /**main*/
    "nav-home": "Home",
    "nav-benefits": "Benefits",
    "nav-pricing": "Pricing",
    "nav-testimonies": "Testimonies",
    "nav-for-enterprice": "For enterprises",
    "nav-contact": "Contact",
    "nav-login": "Login",
    "nav-signup": "Sign Up",
    "RentalPE-title": "Give your property a second chance with our platform!",
    "RentalPE-description":
      "Get a personalized experience, manage your utilities, track the progress and increase your property value.",
    "free": "Start Free Trial",
    "plan": "Select a Plan",
    "benefits-title": "Benefits",
    "smart": "Smart Monitoring of Energy, Security, and Use",
    "smart-description":
      "Our IoT-powered remodeling goes beyond aesthetics; it equips properties with connected systems that track energy efficiency, security, and occupancy in real time. Whether you live in your property or rent it out, you’ll have a complete view of its performance from a single dashboard.",
    "increase": "Increase the Value of Your Property",
    "increase-description":
      "Turn every renovation into a profitable investment. By integrating smart devices such as sensors, cameras, and automated climate systems, future tenants and buyers will be more attracted to spaces that are modern, secure, and energy-efficient.",
    "simple": "Simple and Centralized Management",
    "simple-description":
      "Forget the chaos of handling remodels manually. With RentallPe, all your projects, payments, contracts, and reports are unified in one digital platform.",
    "pricing-title": "Our Prices",
    "month": " / month",
    "starter": "Starter",
    "starter-feature1": "Home Monitoring",
    "starter-feature2": "Energy Monitoring",
    "starter-feature3": "2 WiFi Cameras",
    "starter-feature4": "4 Occupancy Sensors",
    "starter-feature5": "5 Smart Locks",
    "house-starter": "For small houses",
    "select-starter": "Get started",
    "pro": "Professional",
    "pro-feature1": "Everything in Starter, plus:",
    "pro-feature2": "4 Extra WiFi cameras",
    "pro-feature3": "6 Extra Occupancy Sensors",
    "pro-feature4": "1 Garage-Door Sensor",
    "pro-feature5": "Smart Lighting System",
    "pro-feature6": "Automated Curtains",
    "house-pro": "For big houses",
    "select-pro": "Get started",
    "premium": "Premium",
    "premium-feature1": "Everything in Professional per house, plus:",
    "premium-feature2": "Smart Irrigation Systems",
    "premium-feature3": "Smart Thermostats",
    "house-premium": "Up to 3 big houses",
    "select-premium": "Get started",
    "testimonies-title": "What Our Users Say",
    "user1-name": "Laura G.",
    "user1-plan": "Starter Plan",
    "user1-feedback":
      '"With the Starter Plan, I can finally monitor my apartment remotely.The smart locks and cameras make me feel secure, and I no longerworry about forgetting contract renewals or maintenance dates.For a small place like mine, it’s exactly what I needed."',
    "user2-name": "Carlos R.",
    "user2-plan": "Professional Plan",
    "user2-feedback":
      "“I rent some unused rooms in my house and used to struggle withkeeping everything under control. The Professional Plan gave meoccupancy sensors and garage monitoring, so now I know when theservices are being used. It saves me time and gives me fullvisibility.”",
    "user3-name": "Elena M.",
    "user3-plan": "Premium Plan",
    "user3-feedback":
      '"We live in one house and rent out two others. With the Premium Plan,I can monitor all three properties from one dashboard. The extrasensors and cameras help me detect issues before they becomeexpensive, and the smart locks make tenant changes seamless.It’s peace of mind for my family and our investments."',
    "enterprises-title": "For Enterprises",
    "enterprises-get-started": "Get started",
    "enterprise-benefits": "",     
    "benefits-title": "Key Benefits for Your Business",
    "enterprise-pitch": "",         
    "pitch-title":
      "Transform your commercial spaces with<br>technology-driven renovations",
    "pitch-text":
      "RentallPe empowers companies to remodel and monitor their spaces with efficiency, transparency, and smart automation.",
    "deliverables-title": "What You Get",
    "footer-brand": "RentallPe",
    "footer-description":
      "At RentallPe our primary mission is to remodel and modernize real-estate spaces, turning them into smart, efficient and valuable assets.",
    "footer-cta": "Remodel your first Property",
    "footer-contact-title": "Contact",
    "footer-email": "Email: support@rentallpe.com",
    "footer-address": "Offices: 456 Main Street, Lima, Peru",
    "footer-phone": "Phone: +51 913 123 123",
    //!  /**login*/
    "login": "Login",
    "register": "Register",
    "password?": "forgot your password?",
    //!  /**register*/
    "register": "Register",
    "log-in": "Log In",
    "name": "Name",
    "email": "Email",
    "password": "Password",
    "repit-password": "Repit Password"
  },

  ES: {
    //!  /**main*/
    "nav-home": "Inicio",
    "nav-benefits": "Beneficios",
    "nav-pricing": "Precios",
    "nav-testimonies": "Testimonios",
    "nav-for-enterprice": "Para empresas",
    "nav-contact": "Contacto",
    "nav-login": "Iniciar sesión",
    "nav-signup": "Regístrate",
    "RentalPE-title":
      "¡Dale una segunda vida a tu propiedad con nuestra plataforma!",
    "RentalPE-description":
      "Obtén una experiencia personalizada, gestiona tus consumos, sigue el progreso y aumenta el valor de tu propiedad.",
    "free": "Prueba gratis",
    "plan": "Elegir un plan",
    "benefits-title": "Beneficios",
    "smart": "Monitoreo inteligente de energía, seguridad y uso",
    "smart-description":
      "Nuestra remodelación con IoT va más allá de la estética: equipa tu propiedad con sistemas conectados que miden eficiencia energética, seguridad y ocupación en tiempo real.",
    "increase": "Incrementa el valor de tu propiedad",
    "increase-description":
      "Convierte cada remodelación en una inversión rentable. Con dispositivos inteligentes, los futuros inquilinos y compradores se sentirán atraídos por espacios modernos, seguros y eficientes.",
    "simple": "Gestión simple y centralizada",
    "simple-description":
      "Olvídate del caos de las remodelaciones manuales. Con RentallPe, todos tus proyectos, pagos, contratos y reportes se unifican en una sola plataforma digital.",
    "pricing-title": "Planes",
    "month": " / mensual",
    "starter": "Starter",
    "starter-feature1": "Monitoreo del hogar",
    "starter-feature2": "Monitoreo de energía",
    "starter-feature3": "2 cámaras WiFi",
    "starter-feature4": "4 sensores de ocupación",
    "starter-feature5": "5 cerraduras inteligentes",
    "house-starter": "Para casas pequeñas",
    "select-starter": "Comenzar",
    "pro": "Profesional",
    "pro-feature1": "Todo lo del Starter, y además:",
    "pro-feature2": "4 cámaras WiFi extra",
    "pro-feature3": "6 sensores de ocupación extra",
    "pro-feature4": "1 sensor de puerta de garaje",
    "pro-feature5": "Sistema de iluminación inteligente",
    "pro-feature6": "Cortinas automatizadas",
    "house-pro": "Para casas grandes",
    "select-pro": "Comenzar",
    "premium": "Premium",
    "premium-feature1": "Todo lo del Profesional por casa, y además:",
    "premium-feature2": "Sistemas de riego inteligentes",
    "premium-feature3": "Termostatos inteligentes",
    "house-premium": "Hasta 3 casas grandes",
    "select-premium": "Comenzar",
    "testimonies-title": "Lo que dicen nuestros usuarios",
    "user1-name": "Laura G.",
    "user1-plan": "Plan Starter",
    "user1-feedback":
      "Con el Plan Starter, por fin puedo monitorear mi departamento de forma remota. Las cerraduras inteligentes y las cámaras me hacen sentir segura, y ya no me preocupa olvidar las renovaciones de contrato o las fechas de mantenimiento. Para un lugar pequeño como el mío, es exactamente lo que necesitaba.»",
    "user2-name": "Carlos R.",
    "user2-plan": "Plan Profesional",
    "user2-feedback":
      "«Alquilo algunas habitaciones sin usar de mi casa y antes era difícil mantener todo bajo control. El Plan Profesional me proporcionó sensores de ocupación y monitoreo del garaje, así que ahora sé cuándo se usan los servicios. Me ahorra tiempo y me da visibilidad total.»",
    "user3-name": "Elena M.",
    "user3-plan": "Plan Premium",
    "user3-feedback":
      "«Vivimos en una casa y alquilamos otras dos. Con el Plan Premium puedo monitorear las tres propiedades desde un solo panel. Los sensores y cámaras adicionales me ayudan a detectar problemas antes de que se vuelvan costosos, y las cerraduras inteligentes facilitan el cambio de inquilinos. Es tranquilidad para mi familia y nuestras inversiones.»",
    "enterprises-title": "Para Empresas",
    "enterprises-get-started": "Empezar",
    "benefits-title": "Beneficios clave para tu negocio",
    "pitch-title":
      "Transforma tus espacios comerciales<br>con remodelaciones tecnológicas",
    "pitch-text":
      "RentallPe ayuda a las empresas a remodelar y monitorear sus espacios con eficiencia, transparencia y automatización inteligente.",
    "deliverables-title": "Qué obtienes",
    "footer-brand": "RentallPe",
    "footer-description":
      "En RentallPe nuestra misión es remodelar y modernizar espacios inmobiliarios, convirtiéndolos en activos inteligentes, eficientes y valiosos.",
    "footer-cta": "Remodela tu primera propiedad",
    "footer-contact-title": "Contacto",
    "footer-email": "Correo: support@rentallpe.com",
    "footer-address": "Oficinas: Calle Principal 456, Lima, Perú",
    "footer-phone": "Teléfono: +51 913 123 123",
    //!  /**login*/
    "login": "Iniciar sesión",
    "register": "Regístrate",
    "password?": "¿Olvidaste tu contraseña?",
    //!  /**register*/
    "register": "Regístrate",
    "log-in": "Iniciar sesión",
    "name": "Nombre",
    "email": "Correo",
    "password": "Contraseña",
    "repit-password": "Repetir Contraseña"
  }
};
